[build]
builder = "NIXPACKS"

[phases.setup]
aptPkgs = [
  "fonts-dejavu-core",
  "libjpeg-dev",
  "libpng-dev",
  "libgif-dev",
  "libgl1",
  "libfreetype6",
  "libc6"
]

[start]
cmd = "node server.js"
